### ISSUE TITLE
Avoid ugly Invalid JSON error in console

### ISSUE THREAD

**Issue by mmatos** [mumuki/mumuki-wollok-server#10]
This is what I see when I input something that is not a valid reference in the console:

**ム ble**
Invalid JSON {"wollokVersion":"1.4.3","compilation":{"issues":[{"severity":"ERROR","code":"org.eclipse.xtext.diagnostics.Diagnostic.Linking","message":"Couldn't resolve reference to Referenciable 'ciudad'.","lineNumber":57,"offset":878,"length":6,"uri":"__synthetic0.wpgm","syntaxError":false,"data":[]},{"severity":"ERROR","code":"org.eclipse.xtext.diagnostics.Diagnostic.Linking","message":"Couldn't resolve reference to Referenciable 'ble'.","lineNumber":75,"offset":1232,"length":3,"uri":"__synthetic0.wpgm","syntaxError":false,"data":[]},{"severity":"ERROR","code":"METHOD_MUST_HAVE_OVERRIDE_KEYWORD","message":"Method must be marked as override, since it overrides a superclass method","lineNumber":29,"offset":411,"length":8,"uri":"__synthetic0.wpgm","syntaxError":false,"data":[]},{"severity":"ERROR","code":"METHOD_MUST_HAVE_OVERRIDE_KEYWORD","message":"Method must be marked as override, since it overrides a superclass method","lineNumber":59,"offset":940,"length":8,"uri":"__synthetic0.wpgm","syntaxError":false,"data":[]}]}:
757: unexpected token at '{"wollokVersion":"1.4.3","compilation":{"issues":[{"severity":"ERROR","code":"org.eclipse.xtext.diagnostics.Diagnostic.Linking","message":"Couldn't resolve reference to Referenciable 'ciudad'.","lineNumber":57,"offset":878,"length":6,"uri":"__synthetic0.wpgm","syntaxError":false,"data":[]},{"severity":"ERROR","code":"org.eclipse.xtext.diagnostics.Diagnostic.Linking","message":"Couldn't resolve reference to Referenciable 'ble'.","lineNumber":75,"offset":1232,"length":3,"uri":"__synthetic0.wpgm","syntaxError":false,"data":[]},{"severity":"ERROR","code":"METHOD_MUST_HAVE_OVERRIDE_KEYWORD","message":"Method must be marked as override, since it overrides a superclass method","lineNumber":29,"offset":411,"length":8,"uri":"__synthetic0.wpgm","syntaxError":false,"data":[]},{"severity":"ERROR","code":"METHOD_MUST_HAVE_OVERRIDE_KEYWORD","message":"Method must be marked as override, since it overrides a superclass method","lineNumber":59,"offset":940,"length":8,"uri":"__synthetic0.wpgm","syntaxError":false,"data":[]}]}':

-----
/var/lib/gems/2.0.0/bundler/gems/mumukit-d524ec65fe03/lib/mumukit/json.rb:7:in `rescue in pretty_parse'
/var/lib/gems/2.0.0/bundler/gems/mumukit-d524ec65fe03/lib/mumukit/json.rb:5:in `pretty_parse'
/var/www/corso/runners/mumuki-wollok-server/lib/wollok_hook.rb:4:in `run!'
/var/lib/gems/2.0.0/bundler/gems/mumukit-d524ec65fe03/lib/mumukit/server/test_server.rb:86:in `compile_and_run'
/var/lib/gems/2.0.0/bundler/gems/mumukit-d524ec65fe03/lib/mumukit/server/test_server.rb:61:in `run_query!'
/var/lib/gems/2.0.0/bundler/gems/mumukit-d524ec65fe03/lib/mumukit/server/test_server.rb:53:in `block in query!'
/var/lib/gems/2.0.0/bundler/gems/mumukit-d524ec65fe03/lib/mumukit/server/test_server.rb:94:in `respond_to'
/var/lib/gems/2.0.0/bundler/gems/mumukit-d524ec65fe03/lib/mumukit/server/test_server.rb:52:in `query!'
/var/lib/gems/2.0.0/bundler/gems/mumukit-d524ec65fe03/lib/mumukit/server/app.rb:55:in `block in <class:App>'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `[]'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
/var/lib/gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
/var/lib/gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
/var/lib/gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
/var/lib/gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
/var/lib/gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
/var/lib/gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
/var/lib/gems/2.0.0/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
/var/lib/gems/2.0.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:212:in `call'
/var/lib/gems/2.0.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/show_exceptions.rb:25:in `call'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
/var/lib/gems/2.0.0/gems/puma-3.4.0/lib/puma/configuration.rb:224:in `call'
/var/lib/gems/2.0.0/gems/puma-3.4.0/lib/puma/server.rb:569:in `handle_request'
/var/lib/gems/2.0.0/gems/puma-3.4.0/lib/puma/server.rb:406:in `process_client'
/var/lib/gems/2.0.0/gems/puma-3.4.0/lib/puma/server.rb:271:in `block in run'
/var/lib/gems/2.0.0/gems/puma-3.4.0/lib/puma/thread_pool.rb:114:in `call'
/var/lib/gems/2.0.0/gems/puma-3.4.0/lib/puma/thread_pool.rb:114:in `block in spawn_thread'
-----

**Comment by flbulgarelli** [comment]
This is an issue of the wollok server component at http://server.wollok.org. The server is returning sometimes a broken response and thus mumuki cannot parse it.  

Apparently @npasserini has solved it but it is not yet deployed.
